== Modelltypen

INTERLIS-Modelle werden für verschiedene Zwecke eingesetzt. Entsprechend muss dies beim Modellieren berücksichtigt werden. Nicht in jedem Fall werden oder müssen sowohl ein Erfassungs- und eine Publikationsmodell geschrieben werden.

=== Erfassungsmodell

Erfassungsmodelle dienen der Erfassung und Nachführung von Daten in der Datenbank. Als Werkzeug zur Bewirtschaftung der Daten wird _QGIS_ eingesetzt. Der Fokus bei der Modellierung liegt auf den Verzicht von Redundanzen, d.h. die Modelle sind normalisiert. So werden z.B. zwischen den einzelnen Klassen Beziehungen modelliert und Aufzähltypen modelliert, um allfällige Redundanzen zu vermeiden. Im Zusammenspiel mit _QGIS_ entsteht somit eine «generische» Erfassungsfachschale.

=== Publikationsmodell

Aufgrund der Normalisierung eignen sich Daten im Erfassungsmodell nicht für die Publikation in einem Web GIS oder als «einfacher» Layer in _QGIS_. Die für den Benutzer wichtigen Informationen sind in einem Erfassungsmodell oftmals auf verschiedene Klassen resp. Datenbanktabellen verteilt. Für die reine Darstellung und das einfache Abfragen von Informationen ist ein simpleres Modell – das Publikationsmodell – zu erarbeiten. Hauptmerkmale eines Publikationsmodelles:

- Verzicht auf Beziehungen (Assoziationen) zwischen Klassen.
- Eine Geometriespalte pro Klasse.
- Der Inhalt kann zu jedem Zeitpunkt und automatisiert aus dem Erfassungsmodell und weiterer vorhandener Daten abgeleitet werden.

Es wird kein zusätzliches Datenabgabemodell angestrebt.

Aufzähltypen: Damit Aufzähltypen sinnvoll im Web GIS Client eingesetzt werden können, müssen zwei Bedinungen erfüllt sein: Jeder Aufzähltyp muss einen Kommentar erhalten und es braucht in der Datentabelle eine zusätzliche Spalte, die neben dem Aufzähltyp-Wert auch den Kommentar (den «schönen» Text) zum Aufzähltyp-Wert speichert. Für diese zweite Bedingung muss `ili2pg` erweitert werden. Für Publikationsmodelle, die nicht im Web GIS Client publiziert werden, gilt diese zweite Bedingung nicht. Falls keine Aufzähltypen im Publikationsmodell modelliert werden, kann man nicht nachträglich in der Metadatenbank einen Aufzähltypen «erfinden».

=== Seitenwagenmodell

Ein Seitenwagenmodell ist strukturell ein Publikationsmodell, liegt aber in der Erfassungsdatenbank. Es wird für den CCC-Cache verwendet, d.h. die externe Fachanwendung schreibt via Data-Service in die Erfassungsdatenbank.

=== Validierungsmodell

Das Validierungsmodell dient zur Definition von zusätzlichen Prüfungen mit der Software _ilivalidator_. In diesem Modell müssen zuerst Views erstellt werden. In diesen Views können mit Constraints die zusätzlichen Prüfungen definiert werden. Ein Beispiel findet sich http://geo.so.ch/models/ARP/SO_Nutzungsplanung_20171118_Validierung_20171120.ili[hier].

Weitergehende Informationen zu den Modelltypen gibt es in der https://intraso.rootso.org/verwaltung/bau-und-justiz/amt-fuer-geoinformation/dokumente-und-grundlagen/veranstaltungen-workshops/[Präsentation] des AGI vom 29. August 2017 zum Thema «Arbeiten mit einem Datenmodell».

=== Extension-Functions-Modell

Zum jetzigen Zeitpunkt (2019-03-21) gibt es _ein_ Modell (`SO_FunctionsExt`), in welchem zusätzliche Prüffunktionen deklariert werden. Die Funktionen selber werden in Java https://github.com/sogis/ilivalidator-custom-functions[implementiert]. Der Modellnamen dieses Modelles ist statisch, damit nicht bei jedem neuen Release sämtliche Validierungsmodelle, welche dieses Modell importieren, nachgeführt werden müssen. Dies bedingt jedoch eine strenge Stabilität der Funktionssignaturen. 

Das Modell `SO_FunctionsExt` muss noch in die offizielle INTERLIS-Modellablage des AGI migriert werden und befindet sich heute im Quellcode des ilivalidator-web-service.