== Modellierungsregeln

=== Modellierungssprache / Compiler

#101:: Modellierungssprache ist INTERLIS 2.3 gemäss Referenzhandbuch vom 13. April 2006.

#102:: Für die Kontrolle der Datenmodelle wird der INTERLIS-Compiler Version 4.5.22 vom 7. April 2016 (oder höher) eingesetzt.

#103:: Die verwendete Compiler-Version ist im Modell-Header anzugeben.

#104:: Der Namensraum für Modelle ist http://geo.so.ch/models/AMT wobei das entsprechende Amt angegeben wird.


=== Modellname / Version / Formatierung

#201:: Die Benennung von Modell- und UML- Dateien erfolgt nach folgendem Schema:

kk_ds_n*_[Publikation]_v*[_Publikation_v*].ili/.uml

kk: Kantonskürzel (`SO`)

ds: Kürzel Amt / Dienststelle (`AV`)

n*: Sprechender Name des Modells (`Nachfuehrungskreise`)

v*: Version des Modells im Format JJJJMMTT (`20160407`)

Für den Dateinamen des Publikationsmodelles wird «Publikation» hinzugefügt. Für den Dateinamen des Validierungsmodells wird dem Dateinamen des zu validierenden Modelles «Validierung» (inkl. Datum) hinzugefügt.

#202:: Die Benennung von Modellen erfolgt nach folgendem Schema:

kk_ds_n*_v*

kk: Kantonskürzel (`SO`)

ds: Kürzel Amt / Dienststelle (`AV`)

n*: Sprechender Name des Modells (`Nachfuehrungskreise`)

v*: Version des Modells im Format JJJJMMTT (`20160407`)

Der Modellnamen des Validierungsmodelles und des Publikationsmodells wird analog der Regel für Dateinamen gewählt.

#203:: Die Metaattribute `File`, `Title`, `shortDescription`, `Issuer` und `technicalContact` sind im Header der Modelldatei zu erfassen.

#204:: Die Änderungshistorie wird im Header der Modelldatei dokumentiert.

#205:: Für die Formatierung der Modelldateien dürfen keine Tabulatoren verwendet werden.

#206:: In Kommentaren sollen Umlaute verwendet werden. Dies führt momentan aber noch zu Problemen beim Import in die Datenbank (temporäre Lösung: keine Umlaute verwenden). Dieses Verhalten soll aber 2018 korrigiert werden.

#207:: Im Header der Modelldatei muss der Modelltyp angegeben werden («Erfassungsmodell», «Publikationsmodell», «Validierungsmodell»). 

#208:: Die Version (= Datum) des Modelles ist (via UML-Editor) anzugeben. `VERSION "2017-01-19"`

#209:: Jedes Attribut muss mit einem Kommentar versehen werden, welcher das Attribut sinnvoll beschreibt.

=== Namenskonvention

#301:: Alle Modellelemente (Modellnamen, Topics, Klassen, Attribute etc.) werden ausschliesslich auf Deutsch bezeichnet.

#302:: Namen von Topics, Klassen, Assoziationen und Attributen sollte nicht länger als 29 Zeichen sein.

#303:: Topic-Namen: Gross- und Kleinschrift mit Underscore als Trennzeichen. Plural.

#304:: Klassen-Namen: Gross- und Kleinschrift mit Underscore als Trennzeichen. Singular.

#305:: Attribut-Namen: Gross- und Kleinschrift mit Underscore als Trennzeichen. Singular.

#306:: Die Verwendung von reservierten Namen ist nicht erlaubt.

=== Modellstruktur

#401:: Es müssen die Geometrietypen aus dem CHBase-Modell `GeometryCHLV95_V1` verwendet werden.

#402:: Für Kantonskürzel muss `CHCantonCode` aus dem CHBase-Modell `CHAdminCodes_V1` verwendet werden

#403:: BFS-Nummern sind als Wertebereich 0 .. 9999 zu definieren.

=== Einschränkungen zum Gebrauch von INTERLIS 2.3

#501:: Views dürfen nur in Validierungsmodellen verwendet werden.

#502:: Für `TEXT` muss immer eine konkrete Länge angegeben werden.

#503:: Externe Objektkataloge und Codelisten dürfen nicht verwendet werden.

=== Konsistenzbedingungen

#601:: Die Kardinalitäten von Rollen muss erfasst werden.

#602:: UNIQUE-Bedingungen müssen erfasst werden.

#603:: Als OID wird `INTERLIS.UUIDOID` verwendet.

=== Darstellungsinformationen

#701:: Textpositionen werden nur definiert, wenn diese schwer aus den Daten berechnet werden können oder spezielle Anforderungen an die Darstellung bestehen.

#702:: Für Labelorientierungen etc. wird die Einheit `Units.Angle_Degree` verwendet.

=== Allgemeines

#801:: Allgemeiner Grundsatz: Es wird nur die IST-Situation beschrieben. Also weder Archivierung noch Historisierung respektive die dafür benötigten Attribute.



=== Beispielheader

....
INTERLIS 2.3; 
/**  
* !!------------------------------------------------------------------------------
* !! Version    | wer | Ãnderung 
* !!------------------------------------------------------------------------------
* !! 2015-05-13 | SK  | Modell (v26) für Pilot durch Stefan Keller (SK) erstellt 
* !! 2016-11-11 | SK  | Überarbeitung auf Version 32 (dm_npl_ktso_v32_LV95_ili2.ili)
* !! 2016-11-29 | OJ  | Tech. Review und Finalisierung durch Oliver Jeker (AGI)
* !! 2017-01-05 | OJ  | Korrektur Beziehungsrollennamen = Klassennamen
* !! 2017-09-01 | al  | - Lockerung der Beziehung Dokument <-> Geometrie
* !!            |     | - NP_Typ_Kanton_Grundnutzung mit N134 ergänzt
* !!            |     | - NP_Typ_Kanton_Ueberlagernd_Flaeche mit N812,N813 und
* !!            |     |   N820-823 ergänzt
* !!            |     | - Rechtschreibung bei Ueberbauungsziffer
* !!            |     | - Modell mit Beschreibung ergänzt
* !! 2017-09-15 | al  | OID AS INTERLIS.UUIDOID wieder eingefügt
* !! 2017-11-18 | sz  | - OID AS INTERLIS.UUIDOID für sämtliche Klassen
* !!            |     | - Zusätzliche Assoziation Geometrie <-> Dokument gelöscht
* !!            |     | - Klasse Plandokument gelöscht
* !!==============================================================================
*/
!!@ technicalContact = "mailto:agi@bd.so.ch"; 
!!@ furtherInformation = "http://geo.so.ch/handbuch/nutzungsplanung"; 
MODEL SO_ARP_Nutzungsplanung_20171118(de) 
  AT "http://geo.so.ch/models/ARP" 
  VERSION "2017-11-18" = 

END SO_ARP_Nutzungsplanung_20171118.
....
