== Werkzeuge

Für die verschiedenen Modellierungsprozesse stehen passende Werkzeuge zur Verfügung.

=== UML/INTERLIS-Editor

Der http://umleditor.org/[UML/INTERLIS-Editor] dient der Modellierung von INTERLIS-Modellen mittels UML-Diagrammen. Er benötigt Java und kann lokal installiert und verwendet werden. Die Lernkurve ist relativ steil und die Bedienung gewöhnungsbedürftig. Mit dem Verständnis von INTERLIS als Modellierungssprache wächst auch die Verständnis für die Bedienung des _UML/INTERLIS-Editors_. Als Einstiegshilfe dient die Wikiseite https://geoweb.rootso.org/redmine/projects/sogiswiki/wiki/Modelle_modellieren[Modelle modellieren].

=== ili2c

Mittels https://sourceforge.net/projects/umleditor/files/ili2c/[INTERLIS-Compiler] kann das INTERLIS-Modell syntaktisch geprüft werden. Die Software ist bereits im _UML/INTERLIS-Editor_ eingebaut und muss nicht zwingend separat installiert werden.

Folgende Version ist zu verwenden: 4.5.22 oder höher

=== ili2pg

http://www.eisenhutinformatik.ch/interlis/ili2pg/[Ili2pg] erstellt aufgrund eines INTERLIS-Modelles ein Schema mit leeren Tabellen in einer PostgreSQL/PostGIS-Datenbank. Es kann auch INTERLIS-Transferdateien importieren oder aus einer Datenbank Daten in eine Transferdatei exportieren.

Es wird Version XXXXXX (TODO) verwendet.

Mit `ili2gpkg` und `ili2fgdb` stehen Derivate für GeoPackage und FileGeodatabase zur Verfügung.

=== ilivalidator

Dank des https://github.com/claeis/ilivalidator>[ilivalidators] kann eine INTERLIS-Transferdatei auf ihre Modellkonformität geprüft werden. Die Software ist ebenfalls in _ili2pg_ eingebaut und ist standardmässig aktiviert und muss mit `--disableValidation` ausgeschaltet werden.

=== QGIS-Projektgenerator

Das QGIS-Plugin «QGIS-Projektgenerator» (QGIS 3 only) erstellt anhand eines INTERLIS-Modelles resp. der in der Datenbank angelegten Tabellen automatisch ein QGIS-Projekt mit bereits vorkonfigurierten und verknüpften Formularen. Für grössere Modelle wird man in Zukunft sicher darauf aufbauen können. (Oliver Jeker war Mitglied der Arbeitsgruppe und Sandra Curiger hat bereits erste Tests durchgeführt.)
